<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1tihBjO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1tihBjO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1tihBjO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1tihBjO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1tihBjO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1tihBjO',
    'container.build_id' => '5a4d7e92',
    'container.build_time' => 1578923505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1tihBjO');
