<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'api_cinema_admin' => [[], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::index'], [], [['text', '/api/cinema/admin']], [], []],
    'api_cinemas' => [[], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::listeCinemas'], [], [['text', '/api/cinemas']], [], []],
    'api_detail_cinema' => [['cinema'], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::detailCinema'], [], [['variable', '/', '[^/]++', 'cinema'], ['text', '/api/cinemas']], [], []],
    'api_add_cinema' => [[], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::addCinema'], [], [['text', '/api/cinemas']], [], []],
    'api_update_cinema' => [['cinema'], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::updateCinema'], [], [['variable', '/', '[^/]++', 'cinema'], ['text', '/api/cinemas']], [], []],
    'api_delete_cinema' => [['cinema'], ['_controller' => 'App\\Controller\\ApiCinemaAdminController::deleteCinema'], [], [['variable', '/', '[^/]++', 'cinema'], ['text', '/api/cinemas']], [], []],
    'liste_cinemas' => [[], ['_controller' => 'App\\Controller\\CinemaAdminController::listeCinemas'], [], [['text', '/admin/cinemas/']], [], []],
    'liste_films' => [[], ['_controller' => 'App\\Controller\\CinemaAdminController::listeFilms'], [], [['text', '/admin/films/']], [], []],
    'film_description' => [['idFilm'], ['_controller' => 'App\\Controller\\CinemaAdminController::obtenirUnFilm'], ['idFilm' => '\\d+'], [['variable', '/', '\\d+', 'idFilm'], ['text', '/admin/films']], [], []],
    'detail_cinema' => [['cinema'], ['_controller' => 'App\\Controller\\CinemaAdminController::detailCinema'], [], [['variable', '/', '[^/]++', 'cinema'], ['text', '/admin/cinemas']], [], []],
];
